name: on delete branch

on: delete

jobs:
  delete-ghpages:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
      - run: echo ${{github.ref}},${{github.ref_name}},${{github.ref}},${{github.base_ref}},${{github.head_ref}}
      # - run: mkdir publish && touch publish/.gitkeep
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./publish
      #     destination_dir: ${{ github.ref_name }}
